<a href="https://colab.research.google.com/github/thegeekybeng/iod_ai_ds_coursework_labs/blob/Module-1-Labs/submission_andrew_yeo_iod_lab_1_1_1b_optional.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# pandas puzzles

Inspired by [100 Numpy exercises](https://github.com/rougier/numpy-100), here are 100* short puzzles for testing your knowledge of [pandas'](http://pandas.pydata.org/) power.

Since pandas is a large library with many different specialist features and functions, these exercises focus mainly on the fundamentals of manipulating data (indexing, grouping, aggregating, cleaning), making use of the core DataFrame and Series objects.

Many of the exercises here are straight-forward in that the solutions require no more than a few lines of code (in pandas or NumPy... don't go using pure Python or Cython!). Choosing the right methods and following best practices is the underlying goal.

The exercises are loosely divided in sections. Each section has a difficulty rating; these ratings are subjective, of course, but should be a seen as a rough guide as to how inventive the required solution is.

If you're just starting out with pandas and you are looking for some other resources, the official documentation  is very extensive. In particular, some good places get a broader overview of pandas are...

- [10 minutes to pandas](http://pandas.pydata.org/pandas-docs/stable/10min.html)
- [pandas basics](http://pandas.pydata.org/pandas-docs/stable/basics.html)
- [tutorials](http://pandas.pydata.org/pandas-docs/stable/tutorials.html)
- [cookbook and idioms](http://pandas.pydata.org/pandas-docs/stable/cookbook.html#cookbook)

## Importing pandas

### Getting started and checking your pandas setup

Difficulty: *easy*

**1.** Import pandas under the alias `pd`.

In [ ]:
import pandas as pd

**2.** Print the version of pandas that has been imported.

In [ ]:
print(pd.__version__)

2.2.2


**3.** Print out all the *version* information of the libraries that are required by the pandas library.

In [ ]:
import pandas as pd
print(pd.show_versions())

/usr/local/lib/python3.11/dist-packages/_distutils_hack/__init__.py:31: UserWarning: Setuptools is replacing distutils. Support for replacing an already imported distutils is deprecated. In the future, this condition will fail. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
  warnings.warn(



INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.11.11.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 6.1.85+
Version               : #1 SMP PREEMPT_DYNAMIC Thu Jun 27 21:05:47 UTC 2024
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : en_US.UTF-8
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.2
numpy                 : 1.26.4
pytz                  : 2025.1
dateutil              : 2.8.2
setuptools            : 75.1.0
pip                   : 24.1.2
Cython                : 3.0.12
pytest                : 8.3.4
hypothesis            : None
sphinx                : 8.1.3
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : 5.3.1
html5lib              : 1.1
pymysql               : None
psycopg2   

## DataFrame basics

### A few of the fundamental routines for selecting, sorting, adding and aggregating data in DataFrames

Difficulty: *easy*

Note: remember to import numpy using:
```python
import numpy as np
```

Consider the following Python dictionary `data` and Python list `labels`:

``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
(This is just some meaningless data I made up with the theme of animals and trips to a vet.)

**4.** Create a DataFrame `df` from this dictionary `data` which has the index `labels`.

In [ ]:
import numpy as np
import pandas as pd

data = {
    'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
    'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
    'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# ✅ Create DataFrame with labels as the index
df = pd.DataFrame(data, index=labels)

**5.** Display a summary of the basic information about this DataFrame and its data (*hint: there is a single method that can be called on the DataFrame*).

In [ ]:
import pandas as pd
data = {
    'animal': ['cat', 'dog', 'snake'],
    'age': [2.5, 3, 1.5],
    'visits': [1, 2, 3],
    'priority': ['yes', 'no', 'yes']
}
df = pd.DataFrame(data)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   animal    3 non-null      object 
 1   age       3 non-null      float64
 2   visits    3 non-null      int64  
 3   priority  3 non-null      object 
dtypes: float64(1), int64(1), object(2)
memory usage: 228.0+ bytes


**6.** Return the first 3 rows of the DataFrame `df`.

In [ ]:
df.head(3)

animal  age  visits priority
0    cat  2.5       1      yes
1    dog  3.0       2       no
2  snake  1.5       3      yes

**7.** Select just the 'animal' and 'age' columns from the DataFrame `df`.

In [ ]:
df[['animal', 'age']]

animal  age
0    cat  2.5
1    dog  3.0
2  snake  1.5

**8.** Select the data in rows `[3, 4, 8]` *and* in columns `['animal', 'age']`.

In [ ]:
import pandas as pd

# Recreate the DataFrame if needed
data = {
    'animal': ['cat', 'dog', 'snake', 'dog', 'cat', 'dog', 'snake', 'cat', 'dog', 'dog'],
    'age': [2.5, 3, 1.5, None, 5, 2, 4.5, None, 7, 3]
}
df = pd.DataFrame(data)

# Check again
print(df.shape)  # Should now have 10 rows
print(df.index)  # Check if RangeIndex(0, 10)

df.loc[[3, 4, 8], ['animal', 'age']]

(10, 2)
RangeIndex(start=0, stop=10, step=1)


animal  age
3    dog  NaN
4    cat  5.0
8    dog  7.0

**9.** Select only the rows where the number of visits is greater than 3.

In [ ]:
print(df.columns)

import pandas as pd

# Recreate the DataFrame if needed
data = {
    'animal': ['cat', 'dog', 'snake', 'dog', 'cat', 'dog', 'snake', 'cat', 'dog', 'dog'],
    'age': [2.5, 3, 1.5, None, 5, 2, 4.5, None, 7, 3],
    'visits': [1, 4, 5, 2, 3, 1, 3, 2, 4, 1]  # 🟢 ADDED 'visits' COLUMN
}
df = pd.DataFrame(data)

# Check again
print(df.shape)  # Should now have 10 rows
print(df.index)  # Check if RangeIndex(0, 10)

df[df['visits'] > 3]

Index(['animal', 'age'], dtype='object')
(10, 3)
RangeIndex(start=0, stop=10, step=1)


animal  age  visits
1    dog  3.0       4
2  snake  1.5       5
8    dog  7.0       4

**10.** Select the rows where the age is missing, i.e. it is `NaN`.

In [ ]:
df[df['age'].isna()]

animal  age  visits priority
d    dog  NaN     3.0      yes
h    cat  NaN     1.0      yes



```
# This is formatted as code
```

**11.** Select the rows where the animal is a cat *and* the age is less than 3.

In [ ]:
df[(df['animal'] == 'cat') & (df['age'] < 3)]

animal  age  visits priority
a    cat  2.5     1.0      yes
f    cat  2.0     3.0       no

**12.** Select the rows the age is between 2 and 4 (inclusive).

In [ ]:
df[(df['age'] >= 2) & (df['age'] <= 4)]

animal  age  visits priority
a    cat  2.5     1.0      yes
b    cat  3.0     3.0      yes
f    cat  2.0     3.0       no
j    dog  3.0     1.0       no

**13.** Change the age in row 'f' to 1.5.

In [ ]:
df.loc[5, 'age'] = 1.5  # If row 'f' is actually at index 5

**14.** Calculate the sum of all visits in `df` (i.e. find the total number of visits).

In [ ]:
total_visits = df['visits'].sum()
print(total_visits)

19.0


**15.** Calculate the mean age for each different animal in `df`.

In [ ]:
df.groupby('animal')['age'].mean()

animal
cat      2.5
dog      5.0
snake    2.5
Name: age, dtype: float64

**16.** Append a new row 'k' to `df` with your choice of values for each column. Then delete that row to return the original DataFrame.

In [ ]:
# Append new row 'k'
df.loc['k'] = ['lion', 4.0, 1, 'yes']

# Delete row 'k'
df = df.drop('k')

# Print updated df
print(df)


  animal  age  visits priority
a    cat  2.5     1.0      yes
b    cat  3.0     3.0      yes
c  snake  0.5     2.0       no
d    dog  NaN     3.0      yes
e    dog  5.0     2.0       no
f    cat  2.0     3.0       no
g  snake  4.5     1.0       no
h    cat  NaN     1.0      yes
i    dog  7.0     2.0       no
j    dog  3.0     1.0       no
5    NaN  1.5     NaN      NaN


**17.** Count the number of each type of animal in `df`.

In [ ]:
df['animal'].value_counts()

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64

**18.** Sort `df` first by the values in the 'age' in *descending* order, then by the value in the 'visits' column in *ascending* order (so row `i` should be first, and row `d` should be last).

In [ ]:
df.sort_values(by=['age', 'visits'], ascending=[False, True])

animal  age  visits priority
i    dog  7.0     2.0       no
e    dog  5.0     2.0       no
g  snake  4.5     1.0       no
j    dog  3.0     1.0       no
b    cat  3.0     3.0      yes
a    cat  2.5     1.0      yes
f    cat  2.0     3.0       no
5    NaN  1.5     NaN      NaN
c  snake  0.5     2.0       no
h    cat  NaN     1.0      yes
d    dog  NaN     3.0      yes

**19.** The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.

In [ ]:
df['priority'] = df['priority'].map({'yes': True, 'no': False})

**20.** In the 'animal' column, change the 'snake' entries to 'python'.

In [ ]:
df['animal'] = df['animal'].replace('snake', 'python')

**21.** For each animal type and each number of visits, find the mean age. In other words, each row is an animal, each column is a number of visits and the values are the mean ages (*hint: use a pivot table*).

In [ ]:
df.pivot_table(values='age', index='animal', columns='visits', aggfunc='mean')


visits  1.0  2.0  3.0
animal               
cat     2.5  NaN  2.5
dog     3.0  6.0  NaN
python  4.5  0.5  NaN

## DataFrames: beyond the basics

### Slightly trickier: you may need to combine two or more methods to get the right answer

Difficulty: *medium*

The previous section was tour through some basic but essential DataFrame operations. Below are some ways that you might need to cut your data, but for which there is no single "out of the box" method.

**22.** You have a DataFrame `df` with a column 'A' of integers. For example:
```python
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
```

How do you filter out rows which contain the same integer as the row immediately above?

You should be left with a column containing the following values:

```python
1, 2, 3, 4, 5, 6, 7
```

In [ ]:
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
df[df['A'] != df['A'].shift()]


A
0  1
1  2
3  3
4  4
5  5
8  6
9  7

**23.** Given a DataFrame of numeric values, say
```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # a 5x3 frame of float values
```

how do you subtract the row mean from each element in the row?

In [ ]:
df.sub(df.mean(axis=1), axis=0)


A
0   0.0
1   0.0
2   0.0
3   0.0
4   0.0
5   0.0
6   0.0
7   0.0
8   0.0
9   0.0
10  0.0

**24.** Suppose you have DataFrame with 10 columns of real numbers, for example:

```python
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
```
Which column of numbers has the smallest sum?  Return that column's label.

In [ ]:
df.sum().idxmin()


'A'

**25.** How do you count how many unique rows a DataFrame has (i.e. ignore all rows that are duplicates)? As input, use a DataFrame of zeros and ones with 10 rows and 3 columns.

```python
df = pd.DataFrame(np.random.randint(0, 2, size=(10, 3)))
```

In [ ]:
df = pd.DataFrame(np.random.randint(0, 2, size=(10, 3)))

df.drop_duplicates().shape[0]

5

The next three puzzles are slightly harder.


**26.** In the cell below, you have a DataFrame `df` that consists of 10 columns of floating-point numbers. Exactly 5 entries in each row are NaN values.

For each row of the DataFrame, find the *column* which contains the *third* NaN value.

You should return a Series of column labels: `e, c, d, h, d`

In [ ]:
nan = np.nan

data = [[0.04,  nan,  nan, 0.25,  nan, 0.43, 0.71, 0.51,  nan,  nan],
        [ nan,  nan,  nan, 0.04, 0.76,  nan,  nan, 0.67, 0.76, 0.16],
        [ nan,  nan, 0.5 ,  nan, 0.31, 0.4 ,  nan,  nan, 0.24, 0.01],
        [0.49,  nan,  nan, 0.62, 0.73, 0.26, 0.85,  nan,  nan,  nan],
        [ nan,  nan, 0.41,  nan, 0.05,  nan, 0.61,  nan, 0.48, 0.68]]

columns = list('abcdefghij')

df = pd.DataFrame(data, columns=columns)

# write a solution to the question here

df.isna().cumsum(axis=1).eq(3).idxmax(axis=1)

0    e
1    c
2    d
3    h
4    d
dtype: object

**27.** A DataFrame has a column of groups 'grps' and and column of integer values 'vals':

```python
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'),
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
```
For each *group*, find the sum of the three greatest values. You should end up with the answer as follows:
```
grps
a    409
b    156
c    345
```

In [ ]:
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'),
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})

# write a solution to the question here

df.groupby('grps')['vals'].nlargest(3).groupby(level=0).sum()


grps
a    409
b    156
c    345
Name: vals, dtype: int64

**28.** The DataFrame `df` constructed below has two integer columns 'A' and 'B'. The values in 'A' are between 1 and 100 (inclusive).

For each group of 10 consecutive integers in 'A' (i.e. `(0, 10]`, `(10, 20]`, ...), calculate the sum of the corresponding values in column 'B'.

The answer should be a Series as follows:

```
A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
```

In [ ]:
df = pd.DataFrame(np.random.RandomState(8765).randint(1, 101, size=(100, 2)), columns = ["A", "B"])

# write a solution to the question here

df.groupby(df['A'] // 10 * 10)['B'].sum()

A
0      635
10     335
20     340
30     296
40     676
50     281
60     511
70     456
80     806
90     788
100    163
Name: B, dtype: int64

## DataFrames: harder problems

### These might require a bit of thinking outside the box...

...but all are solvable using just the usual pandas/NumPy methods (and so avoid using explicit `for` loops).

Difficulty: *hard*

**29.** Consider a DataFrame `df` where there is an integer column 'X':
```python
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
```
For each value, count the difference back to the previous zero (or the start of the Series, whichever is closer). These values should therefore be

```
[1, 2, 0, 1, 2, 3, 4, 0, 1, 2]
```

Make this a new column 'Y'.

In [ ]:
import pandas as pd

# Create DataFrame
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})

# Compute difference from the previous row, filling NaN with the first value
df['Y'] = df['X'].diff().fillna(df['X'])

# Print DataFrame
print(df)


   X    Y
0  7  7.0
1  2 -5.0
2  0 -2.0
3  3  3.0
4  4  1.0
5  2 -2.0
6  5  3.0
7  0 -5.0
8  3  3.0
9  4  1.0


**30.** Consider the DataFrame constructed below which contains rows and columns of numerical data.

Create a list of the column-row index locations of the 3 largest values in this DataFrame. In this case, the answer should be:
```
[(5, 7), (6, 4), (2, 5)]
```

In [ ]:
df = pd.DataFrame(np.random.RandomState(30).randint(1, 101, size=(8, 8)))

**31.** You are given the DataFrame below with a column of group IDs, 'grps', and a column of corresponding integer values, 'vals'.

```python
df = pd.DataFrame({"vals": np.random.RandomState(31).randint(-30, 30, size=15),
                   "grps": np.random.RandomState(31).choice(["A", "B"], 15)})
```

Create a new column 'patched_values' which contains the same values as the 'vals' any negative values in 'vals' with the group mean:

```
    vals grps  patched_vals
0    -12    A          13.6
1     -7    B          28.0
2    -14    A          13.6
3      4    A           4.0
4     -7    A          13.6
5     28    B          28.0
6     -2    A          13.6
7     -1    A          13.6
8      8    A           8.0
9     -2    B          28.0
10    28    A          28.0
11    12    A          12.0
12    16    A          16.0
13   -24    A          13.6
14   -12    A          13.6
```

In [ ]:
df = pd.DataFrame({"vals": np.random.RandomState(31).randint(-30, 30, size=15),
                   "grps": np.random.RandomState(31).choice(["A", "B"], 15)})

df['patched_vals'] = df['vals'].mask(df['vals'] < 0, df.groupby('grps')['vals'].transform('mean'))

**32.** Implement a rolling mean over groups with window size 3, which ignores NaN value. For example consider the following DataFrame:

```python
>>> df = pd.DataFrame({'group': list('aabbabbbabab'),
                       'value': [1, 2, 3, np.nan, 2, 3, np.nan, 1, 7, 3, np.nan, 8]})
>>> df
   group  value
0      a    1.0
1      a    2.0
2      b    3.0
3      b    NaN
4      a    2.0
5      b    3.0
6      b    NaN
7      b    1.0
8      a    7.0
9      b    3.0
10     a    NaN
11     b    8.0
```
The goal is to compute the Series:

```
0     1.000000
1     1.500000
2     3.000000
3     3.000000
4     1.666667
5     3.000000
6     3.000000
7     2.000000
8     3.666667
9     2.000000
10    4.500000
11    4.000000
```
E.g. the first window of size three for group 'b' has values 3.0, NaN and 3.0 and occurs at row index 5. Instead of being NaN the value in the new column at this row index should be 3.0 (just the two non-NaN values are used to compute the mean (3+3)/2)

In [ ]:
import pandas as pd
import numpy as np

# Create DataFrame
df = pd.DataFrame({
    'group': list('aababbabbaba'),
    'value': [1, 2, 3, np.nan, 2, 3, np.nan, 1, 7, 3, np.nan, 8]
})

# Compute rolling mean by group (ignoring NaN)
df['rolling_mean'] = df.groupby('group')['value'].transform(lambda x: x.rolling(3, min_periods=1).mean())

# Print result
print(df)


   group  value  rolling_mean
0      a    1.0      1.000000
1      a    2.0      1.500000
2      b    3.0      3.000000
3      a    NaN      1.500000
4      b    2.0      2.500000
5      b    3.0      2.666667
6      a    NaN      2.000000
7      b    1.0      2.000000
8      b    7.0      3.666667
9      a    3.0      3.000000
10     b    NaN      4.000000
11     a    8.0      5.500000


## Series and DatetimeIndex

### Exercises for creating and manipulating Series with datetime data

Difficulty: *easy/medium*

pandas is fantastic for working with dates and times. These puzzles explore some of this functionality.


**33.** Create a DatetimeIndex that contains each business day of 2015 and use it to index a Series of random numbers. Let's call this Series `s`.

In [ ]:
import pandas as pd
import numpy as np

# Create a DateTimeIndex for 2015
date_rng = pd.date_range(start="2015-01-01", end="2015-12-31", freq='D')

# Create a Series of random numbers indexed by this DateTimeIndex
s = pd.Series(np.random.randn(len(date_rng)), index=date_rng)

# Print sample data
print(s.head())


2015-01-01   -0.394607
2015-01-02   -0.089309
2015-01-03    1.065478
2015-01-04    1.539831
2015-01-05   -0.302006
Freq: D, dtype: float64


**34.** Find the sum of the values in `s` for every Wednesday.

In [ ]:
s[s.index.weekday == 2].sum()


12.840646538780769

**35.** For each calendar month in `s`, find the mean of values.

In [ ]:
s.resample('M').mean()


<ipython-input-40-ceba4aaff27e>:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  s.resample('M').mean()


2015-01-31   -0.129546
2015-02-28    0.396694
2015-03-31   -0.128174
2015-04-30    0.506900
2015-05-31    0.029652
2015-06-30   -0.114666
2015-07-31   -0.294721
2015-08-31   -0.008765
2015-09-30   -0.235725
2015-10-31    0.190337
2015-11-30   -0.039406
2015-12-31    0.165164
Freq: ME, dtype: float64

**36.** For each group of four consecutive calendar months in `s`, find the date on which the highest value occurred.

In [ ]:
s.rolling(4).max().idxmax()


Timestamp('2015-02-21 00:00:00')

**37.** Create a DateTimeIndex consisting of the third Thursday in each month for the years 2015 and 2016.

In [ ]:
third_thursdays = pd.date_range(start="2015-01-01", end="2016-12-31", freq='WOM-3THU')
print(third_thursdays)


DatetimeIndex(['2015-01-15', '2015-02-19', '2015-03-19', '2015-04-16',
               '2015-05-21', '2015-06-18', '2015-07-16', '2015-08-20',
               '2015-09-17', '2015-10-15', '2015-11-19', '2015-12-17',
               '2016-01-21', '2016-02-18', '2016-03-17', '2016-04-21',
               '2016-05-19', '2016-06-16', '2016-07-21', '2016-08-18',
               '2016-09-15', '2016-10-20', '2016-11-17', '2016-12-15'],
              dtype='datetime64[ns]', freq='WOM-3THU')


## Cleaning Data

### Making a DataFrame easier to work with

Difficulty: *easy/medium*

It happens all the time: someone gives you data containing malformed strings, Python, lists and missing data. How do you tidy it up so you can get on with the analysis?

Take this monstrosity as the DataFrame to use in the following puzzles:

```python
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
                               '12. Air France', '"Swiss Air"']})
```
Formatted, it looks like this:

```
            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"
```


(It's some flight data I made up; it's not meant to be accurate in any way.)


**38.** Some values in the the **FlightNumber** column are missing (they are `NaN`). These numbers are meant to increase by 10 with each row so 10055 and 10075 need to be put in place. Modify `df` to fill in these missing numbers and make the column an integer column (instead of a float column).

In [ ]:
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
                               '12. Air France', '"Swiss Air"']})

df['FlightNumber'] = df['FlightNumber'].interpolate().astype(int)


**39.** The **From\_To** column would be better as two separate columns! Split each string on the underscore delimiter `_` to give a new temporary DataFrame called 'temp' with the correct values. Assign the correct column names 'From' and 'To' to this temporary DataFrame.

In [ ]:
df[['From', 'To']] = df['From_To'].str.split('_', expand=True)


**40.** Notice how the capitalisation of the city names is all mixed up in this temporary DataFrame 'temp'. Standardise the strings so that only the first letter is uppercase (e.g. "londON" should become "London".)

In [ ]:
df['From'] = df['From'].str.capitalize()
df['To'] = df['To'].str.capitalize()


**41.** Delete the **From_To** column from `df` and attach the temporary DataFrame 'temp' from the previous questions.

In [ ]:
df = df.drop('From_To', axis=1)


**42**. In the **Airline** column, you can see some extra punctuation and symbols have appeared around the airline names. Pull out just the airline name. E.g. `'(British Airways. )'` should become `'British Airways'`.

In [ ]:
df['Airline'] = df['Airline'].str.extract('([a-zA-Z\s]+)', expand=False).str.strip()


**43**. In the RecentDelays column, the values have been entered into the DataFrame as a list. We would like each first value in its own column, each second value in its own column, and so on. If there isn't an Nth value, the value should be NaN.

Expand the Series of lists into a DataFrame named `delays`, rename the columns `delay_1`, `delay_2`, etc. and replace the unwanted RecentDelays column in `df` with `delays`.

In [ ]:
import pandas as pd

# Sample Data (Ensure 'RecentDelays' is present)
df = pd.DataFrame({
    'From_To': ["London_Paris", "Madrid_Milan", "London_Stockholm", "Budapest_Paks", "Brussels_London"],
    'FlightNumber': [10045, 10055, 10065, 10075, 10085],
    'RecentDelays': [[23, 47], [None], [24, 43, 87], [13], [67, 32]],
    'Airline': ["KLM", "Air France", "British Airways", "Swiss Air", "Lufthansa"]
})

# ✅ Expand 'RecentDelays' into separate columns
delays = df['RecentDelays'].apply(pd.Series)

# ✅ Rename columns dynamically as 'delay_1', 'delay_2', etc.
delays.columns = [f'delay_{i+1}' for i in range(delays.shape[1])]

# ✅ Drop the original 'RecentDelays' column and join expanded columns
df = df.drop(columns=['RecentDelays']).join(delays)

# ✅ Print the final cleaned DataFrame
print(df)


            From_To  FlightNumber          Airline  delay_1  delay_2  delay_3
0      London_Paris         10045              KLM     23.0     47.0      NaN
1      Madrid_Milan         10055       Air France      NaN      NaN      NaN
2  London_Stockholm         10065  British Airways     24.0     43.0     87.0
3     Budapest_Paks         10075        Swiss Air     13.0      NaN      NaN
4   Brussels_London         10085        Lufthansa     67.0     32.0      NaN


The DataFrame should look much better now.
```
   FlightNumber          Airline      From         To  delay_1  delay_2  delay_3
0         10045              KLM    London      Paris     23.0     47.0      NaN
1         10055       Air France    Madrid      Milan      NaN      NaN      NaN
2         10065  British Airways    London  Stockholm     24.0     43.0     87.0
3         10075       Air France  Budapest      Paris     13.0      NaN      NaN
4         10085        Swiss Air  Brussels     London     67.0     32.0      NaN
```